//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v14.2.0+1b21caa
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>About Us</summary>
	[PublishedModel("aboutUs")]
	public partial class AboutUs : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const string ModelTypeAlias = "aboutUs";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<AboutUs, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public AboutUs(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// ceoImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ceoImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops CeoImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "ceoImage");

		///<summary>
		/// ceoImageText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ceoImageText")]
		public virtual string CeoImageText => this.Value<string>(_publishedValueFallback, "ceoImageText");

		///<summary>
		/// ceoParagraph1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ceoParagraph1")]
		public virtual string CeoParagraph1 => this.Value<string>(_publishedValueFallback, "ceoParagraph1");

		///<summary>
		/// ceoParagraph2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ceoParagraph2")]
		public virtual string CeoParagraph2 => this.Value<string>(_publishedValueFallback, "ceoParagraph2");

		///<summary>
		/// ceoParagraph3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ceoParagraph3")]
		public virtual string CeoParagraph3 => this.Value<string>(_publishedValueFallback, "ceoParagraph3");

		///<summary>
		/// ceoParagraph4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ceoParagraph4")]
		public virtual string CeoParagraph4 => this.Value<string>(_publishedValueFallback, "ceoParagraph4");

		///<summary>
		/// ceoParagraph5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ceoParagraph5")]
		public virtual string CeoParagraph5 => this.Value<string>(_publishedValueFallback, "ceoParagraph5");

		///<summary>
		/// ceoParagraph6
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ceoParagraph6")]
		public virtual string CeoParagraph6 => this.Value<string>(_publishedValueFallback, "ceoParagraph6");

		///<summary>
		/// ceoParagraph7
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ceoParagraph7")]
		public virtual string CeoParagraph7 => this.Value<string>(_publishedValueFallback, "ceoParagraph7");

		///<summary>
		/// ceoTextHeadLine
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ceoTextHeadLine")]
		public virtual string CeoTextHeadLine => this.Value<string>(_publishedValueFallback, "ceoTextHeadLine");

		///<summary>
		/// greatReviewsHeadLine1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("greatReviewsHeadLine1")]
		public virtual string GreatReviewsHeadLine1 => this.Value<string>(_publishedValueFallback, "greatReviewsHeadLine1");

		///<summary>
		/// greatReviewsHeadLine2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("greatReviewsHeadLine2")]
		public virtual string GreatReviewsHeadLine2 => this.Value<string>(_publishedValueFallback, "greatReviewsHeadLine2");

		///<summary>
		/// greatReviewsImage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("greatReviewsImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops GreatReviewsImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "greatReviewsImage");

		///<summary>
		/// greatReviewsImageAltText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("greatReviewsImageAltText")]
		public virtual string GreatReviewsImageAltText => this.Value<string>(_publishedValueFallback, "greatReviewsImageAltText");

		///<summary>
		/// greatReviewsQuote
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("greatReviewsQuote")]
		public virtual string GreatReviewsQuote => this.Value<string>(_publishedValueFallback, "greatReviewsQuote");

		///<summary>
		/// greatReviewsRating
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("greatReviewsRating")]
		public virtual string GreatReviewsRating => this.Value<string>(_publishedValueFallback, "greatReviewsRating");

		///<summary>
		/// greatReviewsReviewCompany
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("greatReviewsReviewCompany")]
		public virtual string GreatReviewsReviewCompany => this.Value<string>(_publishedValueFallback, "greatReviewsReviewCompany");

		///<summary>
		/// greatReviewsReviewName
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("greatReviewsReviewName")]
		public virtual string GreatReviewsReviewName => this.Value<string>(_publishedValueFallback, "greatReviewsReviewName");

		///<summary>
		/// greatReviewsTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("greatReviewsTitle")]
		public virtual string GreatReviewsTitle => this.Value<string>(_publishedValueFallback, "greatReviewsTitle");

		///<summary>
		/// largeCardImage1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("largeCardImage1")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops LargeCardImage1 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "largeCardImage1");

		///<summary>
		/// largeCardImage2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("largeCardImage2")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops LargeCardImage2 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "largeCardImage2");

		///<summary>
		/// largeCardImage3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("largeCardImage3")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops LargeCardImage3 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "largeCardImage3");

		///<summary>
		/// largeCardImageAltText1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("largeCardImageAltText1")]
		public virtual string LargeCardImageAltText1 => this.Value<string>(_publishedValueFallback, "largeCardImageAltText1");

		///<summary>
		/// largeCardImageAltText2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("largeCardImageAltText2")]
		public virtual string LargeCardImageAltText2 => this.Value<string>(_publishedValueFallback, "largeCardImageAltText2");

		///<summary>
		/// largeCardImageAltText3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("largeCardImageAltText3")]
		public virtual string LargeCardImageAltText3 => this.Value<string>(_publishedValueFallback, "largeCardImageAltText3");

		///<summary>
		/// largeCardJobTitle1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("largeCardJobTitle1")]
		public virtual string LargeCardJobTitle1 => this.Value<string>(_publishedValueFallback, "largeCardJobTitle1");

		///<summary>
		/// largeCardJobTitle2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("largeCardJobTitle2")]
		public virtual string LargeCardJobTitle2 => this.Value<string>(_publishedValueFallback, "largeCardJobTitle2");

		///<summary>
		/// largeCardJobTitle3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("largeCardJobTitle3")]
		public virtual string LargeCardJobTitle3 => this.Value<string>(_publishedValueFallback, "largeCardJobTitle3");

		///<summary>
		/// largeCardName1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("largeCardName1")]
		public virtual string LargeCardName1 => this.Value<string>(_publishedValueFallback, "largeCardName1");

		///<summary>
		/// largeCardName2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("largeCardName2")]
		public virtual string LargeCardName2 => this.Value<string>(_publishedValueFallback, "largeCardName2");

		///<summary>
		/// largeCardName3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("largeCardName3")]
		public virtual string LargeCardName3 => this.Value<string>(_publishedValueFallback, "largeCardName3");

		///<summary>
		/// ourExpertHeadLine1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertHeadLine1")]
		public virtual string OurExpertHeadLine1 => this.Value<string>(_publishedValueFallback, "ourExpertHeadLine1");

		///<summary>
		/// ourExpertHeadLine2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertHeadLine2")]
		public virtual string OurExpertHeadLine2 => this.Value<string>(_publishedValueFallback, "ourExpertHeadLine2");

		///<summary>
		/// ourExpertTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ourExpertTitle")]
		public virtual string OurExpertTitle => this.Value<string>(_publishedValueFallback, "ourExpertTitle");

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pageTitle")]
		public virtual string PageTitle => this.Value<string>(_publishedValueFallback, "pageTitle");

		///<summary>
		/// showPartialView
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("showPartialView")]
		public virtual string ShowPartialView => this.Value<string>(_publishedValueFallback, "showPartialView");

		///<summary>
		/// smallCardImage1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smallCardImage1")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops SmallCardImage1 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "smallCardImage1");

		///<summary>
		/// smallCardImage2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smallCardImage2")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops SmallCardImage2 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "smallCardImage2");

		///<summary>
		/// smallCardImage3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smallCardImage3")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops SmallCardImage3 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "smallCardImage3");

		///<summary>
		/// smallCardImage4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smallCardImage4")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops SmallCardImage4 => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "smallCardImage4");

		///<summary>
		/// smallCardImageAltText1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smallCardImageAltText1")]
		public virtual string SmallCardImageAltText1 => this.Value<string>(_publishedValueFallback, "smallCardImageAltText1");

		///<summary>
		/// smallCardImageAltText2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smallCardImageAltText2")]
		public virtual string SmallCardImageAltText2 => this.Value<string>(_publishedValueFallback, "smallCardImageAltText2");

		///<summary>
		/// smallCardImageAltText3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smallCardImageAltText3")]
		public virtual string SmallCardImageAltText3 => this.Value<string>(_publishedValueFallback, "smallCardImageAltText3");

		///<summary>
		/// smallCardImageAltText4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smallCardImageAltText4")]
		public virtual string SmallCardImageAltText4 => this.Value<string>(_publishedValueFallback, "smallCardImageAltText4");

		///<summary>
		/// smallCardJobTitle1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smallCardJobTitle1")]
		public virtual string SmallCardJobTitle1 => this.Value<string>(_publishedValueFallback, "smallCardJobTitle1");

		///<summary>
		/// smallCardJobTitle2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smallCardJobTitle2")]
		public virtual string SmallCardJobTitle2 => this.Value<string>(_publishedValueFallback, "smallCardJobTitle2");

		///<summary>
		/// smallCardJobTitle3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smallCardJobTitle3")]
		public virtual string SmallCardJobTitle3 => this.Value<string>(_publishedValueFallback, "smallCardJobTitle3");

		///<summary>
		/// smallCardJobTitle4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smallCardJobTitle4")]
		public virtual string SmallCardJobTitle4 => this.Value<string>(_publishedValueFallback, "smallCardJobTitle4");

		///<summary>
		/// smallCardName1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smallCardName1")]
		public virtual string SmallCardName1 => this.Value<string>(_publishedValueFallback, "smallCardName1");

		///<summary>
		/// smallCardName2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smallCardName2")]
		public virtual string SmallCardName2 => this.Value<string>(_publishedValueFallback, "smallCardName2");

		///<summary>
		/// smallCardName3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smallCardName3")]
		public virtual string SmallCardName3 => this.Value<string>(_publishedValueFallback, "smallCardName3");

		///<summary>
		/// smallCardName4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "14.2.0+1b21caa")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("smallCardName4")]
		public virtual string SmallCardName4 => this.Value<string>(_publishedValueFallback, "smallCardName4");
	}
}
